# Generated by Django 3.2.9 on 2021-12-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUT_AL', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('pragrapg1', models.CharField(max_length=5000)),
                ('pragrapg2', models.CharField(max_length=5000)),
                ('pragrapg4', models.CharField(max_length=5000)),
                ('pragrapg5', models.CharField(max_length=5000)),
                ('pragrapg6', models.CharField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='pirthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
