# Generated by Django 3.2.9 on 2021-12-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUT_AL', '0005_auto_20211212_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='why',
            name='pragrapg1',
            field=models.CharField(blank=True, default='exit', max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='why',
            name='pragrapg2',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
