# Generated by Django 3.2.9 on 2021-12-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUT_AL', '0006_auto_20211212_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeslids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('pragrapg', models.CharField(blank=True, max_length=5000)),
                ('link', models.CharField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
