# Generated by Django 3.2.9 on 2022-01-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUT_AL', '0009_alter_homeslids_pragrapg'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('jop', models.CharField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('degree', models.CharField(blank=True, max_length=1000)),
                ('specialty', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
