# Generated by Django 3.2.9 on 2022-02-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUT_AL', '0017_salam'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='link',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
