# Generated by Django 3.2.9 on 2022-02-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUT_AL', '0018_images_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='autip',
            name='Duration',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='autip',
            name='Duration2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
