# Generated by Django 3.2.9 on 2021-12-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUT_AL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=120)),
                ('phoneno', models.CharField(max_length=20)),
                ('pirthday', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
            ],
        ),
    ]
