# Generated by Django 3.2.9 on 2021-12-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUT_AL', '0007_homeslids'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1500, null=True)),
                ('pragrapg', models.CharField(blank=True, max_length=5000)),
                ('day', models.CharField(blank=True, max_length=5)),
                ('month', models.CharField(blank=True, max_length=5)),
                ('link', models.CharField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
