# Generated by Django 3.2.9 on 2022-01-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUT_AL', '0008_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslids',
            name='pragrapg',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
