# Generated by Django 3.2.9 on 2022-01-12 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AUT_AL', '0011_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutprogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='text',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='autip',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autip',
            name='text',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='autip',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
