# Generated by Django 3.2.9 on 2022-01-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUT_AL', '0012_auto_20220112_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio_Modals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('text', models.CharField(blank=True, max_length=5000)),
            ],
        ),
    ]
