# Generated by Django 3.2.9 on 2022-01-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUT_AL', '0014_auto_20220113_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_members',
            name='linkedin',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
