# Generated by Django 3.2.9 on 2022-01-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUT_AL', '0015_faculty_members_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_modals',
            name='text',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
