# Generated by Django 3.2.9 on 2022-01-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUT_AL', '0016_alter_portfolio_modals_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='salam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, max_length=50, null=True)),
                ('elements', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.TextField(blank=True, max_length=5000)),
                ('text2', models.TextField(blank=True, max_length=5000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
